### ISSUE TITLE
Can't seem to reliably subscribe/unsubscribe

### ISSUE THREAD

**Issue by CallumCoombes** [pusher/pusher-platform-android#21]
So I am calling `PushNotifications.start(getApplicationContext(), "API-KEY");` in my Application class, then in one of my activities I call:

```
public void initPusherFCM() {
        //create subscription channel key
        String subKey = "app." + this.user.getUuid();
        //get list of current subscriptions
        Set<String> subscriptions = PushNotifications.getSubscriptions();

        //if not already subbed to subKey channel
        if (!subscriptions.contains(subKey)) {
            //unsubscribe from any other channels
            PushNotifications.unsubscribeAll();
            //subscribe to subkey channel
            PushNotifications.subscribe(subKey);
        }
    }
```

The problem I have encountered is that unsubscribe and subscribe don't seem to reliably work, and my subscriptions don't seem properly tracked.

I do get these logs
```
PushNotificationsAPI: Successfully subscribed to interest 'CHANNEL1'
PushNotificationsAPI: Successfully unsubscribed to interest 'CHANNEL2'
```

However, when I reopen the app I am again subscribed to CHANNEL2 and not CHANNEL1.

A full flow of what I have done:
1) Added Pusher code and subscribed to CHANNEL2
2) Tested pushing a message to CHANNEL2, which worked fine
3) Used above code to unsubscribe from CHANNEL2 and subscribe to CHANNEL1
4) Tested pushing a message to CHANNEL1, which worked fine
5) Closed and opened the app, upon opening I was subscribed to CHANNEL2 and not CHANNEL1. So the subscription changes I made have been forgotten.
6) Tested opening and closing the app multiple times, tested closing app completely. Every time I open the app I am always subscribed to only CHANNEL2.

Hopefully the issue is clear, it's been a long day!

**Comment by luismfonseca** [comment]
Hi @CallumCoombes,

I followed your steps and couldn't replicate the issue. Can you try this with a new app and paste the source code?

Also, which version of the SDK are you using? If you're not using the latest, can you try that one?

**Comment by hamchapman** [comment]
Closing as stale. Feel free to follow up with more info though!
